"""Milestone 5: render ranked options as an HTML digest.

See project spec §4.6. Reuses the delivery pattern from the existing
theatre-watchlist checker: a single ranked table (Program | Dates | Cabin |
Miles Required | Active Bonus | Effective Amex Points | Cash Baseline | CPP | Notes).
"""

from html import escape

from awardhawk.models import RankedOption

_CSS = """
  * { box-sizing: border-box; }
  body { margin:0; background:#12181f; font-family:'Courier New',Courier,monospace;
         padding:24px 12px; color:#d8e4ea; }
  .email { max-width:820px; margin:0 auto; background:#0c1116;
           border:1px solid #2a3a44; box-shadow:0 16px 44px rgba(0,0,0,0.4); }
  .board-head { padding:22px 26px 16px; border-bottom:2px solid #ffb400; }
  .board-title { font-size:19px; font-weight:700; letter-spacing:0.12em;
                 text-transform:uppercase; color:#ffb400; margin:0; }
  .board-sub { font-size:11px; color:#7c94a1; margin:6px 0 0; letter-spacing:0.04em; }
  table { width:100%; border-collapse:collapse; font-size:12px; }
  thead th { text-align:left; padding:10px 12px; background:#161f27; color:#ffb400;
             text-transform:uppercase; letter-spacing:0.06em; font-size:10.5px;
             border-bottom:1px solid #2a3a44; white-space:nowrap; }
  tbody td { padding:10px 12px; border-bottom:1px solid #1c2932; vertical-align:top; }
  tbody tr:nth-child(even) { background:#0f151b; }
  .cpp { color:#4fd67a; font-weight:700; }
  .points { color:#d8e4ea; }
  .bonus { color:#ffb400; }
  .no-bonus { color:#556873; }
  .notes { color:#7c94a1; font-size:11px; }
  .empty { padding:30px 26px; color:#7c94a1; }
  .footer { padding:16px 26px; font-size:10px; color:#556873; border-top:1px solid #1c2932; }
"""

_HEADERS = [
    "Program", "Dates", "Cabin", "Miles Required", "Active Bonus",
    "Effective Amex Points", "Cash Baseline", "CPP", "Notes",
]


def _render_row(option: RankedOption) -> str:
    award = option.award_result
    bonus = option.applicable_bonus

    bonus_cell = (
        f'<span class="bonus">{bonus.bonus_percent:.0%} → {escape(bonus.to_program)}</span>'
        if bonus is not None
        else '<span class="no-bonus">—</span>'
    )
    cash_cell = f"{option.cash_baseline.fare_amount:,.2f} {escape(option.cash_baseline.currency)}"
    notes_cell = escape(", ".join(option.notes)) if option.notes else ""

    return f"""
    <tr>
      <td>{escape(award.program)}</td>
      <td>{escape(award.date.isoformat())}</td>
      <td>{escape(award.cabin.value)}</td>
      <td class="points">{award.miles_required:,}</td>
      <td>{bonus_cell}</td>
      <td class="points">{option.effective_amex_points:,}</td>
      <td>{cash_cell}</td>
      <td class="cpp">{option.cpp:.2f}¢</td>
      <td class="notes">{notes_cell}</td>
    </tr>
    """


def render_html_digest(options: list[RankedOption]) -> str:
    """Render ranked options as an HTML digest table."""
    if not options:
        body = '<div class="empty">No ranked options available for this run.</div>'
    else:
        rows = "".join(_render_row(option) for option in options)
        header_cells = "".join(f"<th>{h}</th>" for h in _HEADERS)
        body = f"""
        <table>
          <thead><tr>{header_cells}</tr></thead>
          <tbody>{rows}</tbody>
        </table>
        """

    return f"""
    <html><head>
    <meta charset="utf-8">
    <style>{_CSS}</style></head><body>
    <div class="email">
      <div class="board-head">
        <p class="board-title">AwardHawk — YVR → SIN</p>
        <p class="board-sub">Ranked by cents-per-point value</p>
      </div>
      {body}
      <div class="footer">Generated by AwardHawk. Fares and award space are estimates — verify before booking.</div>
    </div>
    </body></html>
    """
